##############################################################################

# This file is for you to edit the paths corresponding to the following:
# - source path of annotation files
# - destination path of your annotation files (leave unchanged if possible)
# - source path of sound files (.wav of .aif) (top most directory)
# - destination path of any plots or spreadsheets

# This file is also for you to edit the threshold value of the detector, to 
# make the detector more sensitive or less sensitive.
#   - Higher threshold will decrease number of false positives but
#   at the cost of overlooking vocalizations.
#   - Lower threshold values will increase number of false positives
#   but more likely also detect false positives.


##############################################################################




###################### 1. DEFINE YOUR RUN ####################################

# what would you like to do?
# chose the run configuration: 
#     - 1 generate annotations
#     - 2 generate new training data from reviewed annotations
#     - 3 train (and evaluate)
run_config: 1

# depending on the main task, chose your predefined settings:
# for generation of annotations, chose:
#     - 1 generate new annotations
#     - 2 filter existing annotations with different threshold
#     - 3 filter existing annotations with sequence criterion - n.i.
#     - 4 generate hourly predictions
#     - 5 generate hourly predictions with varying limits - n.i.
#     - 0 all of the above
# for generation of new training data, chose:
#     - 1 generate new training data from reviewed annotations
#     - 2 generate new training data from reviewed annotations 
#       and fill space between annotations with noise annotations
# for training, chose:
#     - 1 continue training on existing model and save model in the end
#     - 2 evaluate saved model
#     - 3 evaluate model checkpoint
#     - 4 save model specified in advanced config
predefined_settings: 0

####################### 2. DEFINCE YOUR PATHS  ###############################

## Paths
# source path for your sound files (top most directory)
# relevant for option run_config: 1
sound_files_source: '/mnt/d/NOAA/main'

# annotation_source: '/mnt/f/Daten/20221019-Benoit/reviewed_annots'
# relevant for options run_config: 1 and predifined_settings: 2 and 4
generated_annotation_source: '../generated_annotations/2022-12-12_16-11-08'


# source path for your annotations
# relevant for option run_config: 2
#   -> might be easier to just copy annotation files to default location
reviewed_annotation_source: '../generated_annotations/2022-11-27_02'

# destination path for automatically generated annotations
annotation_destination: '../combined_annotations/2022-11-27_02'




####################### 3. DEFINE YOUR PARAMETERS  ###########################

## Model Parameters
# threshold for predictions
thresh: 0.9
# number of annotations above threshold for hourly presence (default = 15)
simple_limit: 15
# threshold for sequence criterion (default = 0.9)
sc_thresh: 0.9
# number of annotations above threshold within 20 consecutive windows
# for hourly presence (default = 3)
sc_limit: 3
# number of consecutive windows that sc_limit has to occur in (default = 20)
sc_con_win: 20

# number of predictions that get computed at once - should be in [20, 2000]
# worth testing out different values to find whats fastest for your machine
prediction_window_limit: 1000