##############################################################################

# This file is for you to edit the paths corresponding to the following:
# - source path of annotation files
# - destination path of your annotation files (leave unchanged if possible)
# - source path of sound files (.wav of .aif) (top most directory)
# - destination path of any plots or spreadsheets

# This file is also for you to edit the threshold value of the detector, to 
# make the detector more sensitive or less sensitive.
#   - Higher threshold will decrease number of false positives but
#   at the cost of overlooking vocalizations.
#   - Lower threshold values will increase number of false positives
#   but more likely also detect false positives.


##############################################################################


## Model Parameters
# threshold for predictions
thresh: 0.5
# number of predictions that get computed at once - should be in [20, 2000]
# worth testing out different values to find whats fastest for your machine
prediction_window_limit: 1000

## Paths
# source path for your annotations
#   -> might be easier to just copy annotation files to default location
annotation_source: '../generated_annotations/2022-11-27_02'
# annotation_source: '/mnt/f/Daten/20221019-Benoit/reviewed_annots'

# destination path for automatically generated annotations
annotation_destination: '../combined_annotations/2022-11-27_02'

# source path for your sound files (top most directory)
sound_files_source: '/mnt/c/Documents and Settings/sa01vk/Documents/SAMOSAS/N1_2kHz_March-April'
# sound_files_source: '../Data/for_manual_annotation/src_to_be_annotated/resampled_2kHz'
